DELIMITER $$
CREATE PROCEDURE errorproc()
BEGIN
	DECLARE CONTINUE HANDLER FOR 1146 SELECT '테이블이 없어요' AS '메시지';
    SELECT * FROM noTable;
    END $$
    DELIMITER ;
CALL errorproc;
-- 1146 == SQLSTATE'42S02'
DROP PROCEDURE IF EXISTS errorproc2;
DELIMITER $$
CREATE PROCEDURE errorproc2()
BEGIN
SHOW ERRORS;
SELECT '오류발생, 작업취소' AS 'MESSAGE';
ROLLBACK;
END;
INSERT INTO usertbl VALUES('LSG','이상구',1988,'서울',NULL,NULL,170,DATE(NOW()));
END $$
DELIMITER ;
