use sqldb;
CREATE DATABASE IF NOT EXISTS partDB;
USE partDB;
CREATE TABLE partTbl(
userId CHAR(8),
name VARCHAR(10) NOT NULL,
birthYear INT NOT NULL,
addr CHAR(2) NOT NULL)
partition by RANGE(birthYear)(
PARTITION part1 VALUES LESS THAN (1971),
PARTITION part2 VALUES LESS THAN (1979),
PARTITION part3 VALUES LESS THAN (MAXVALUE)
);
INSERT INTO partTbl
SELECT userID,name,birthYear,addr FROM sqlDB.usertbl;
SELECT * FROM partTbl ORDER BY birthYear;
-- 파티션 확인하기
SELECT TABLE_SCHEMA,TABLE_NAME,PARTITION_NAME,PARTITION_ORDINAL_POSITION,TABLE_ROWS
FROM INFORMATION_SCHEMA.PARTITIONS
WHERE TABLE_NAME = 'parttbl';
EXPLAIN SELECT * FROM partTbl WHERE birthYear <= 1965;
-- 파티션 관리하기
ALTER TABLE partTbl
REORGANIZE PARTITION part3 INTO(
PARTITION part3 VALUES LESS THAN (1986),
PARTITION part4 VALUES LESS THAN MAXVALUE
);
OPTIMIZE TABLE partTbl;
-- 파티션 합치기
ALTER TABLE partTbl
REORGANIZE PARTITION part1,part2 INTO(
PARTITION part12 VALUES LESS THAN (1979)
);
OPTIMIZE TABLE partTBL;
ALTER TABLE partTbl DROP PARTITION part12;
SELECT * FROM parttbl;
